name: Voxel Definitions - Test & Publish

on:
  push:
    branches: [main]
    paths:
      - '@voxel-definitions/**'
  pull_request:
    branches: [main]
    paths:
      - '@voxel-definitions/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check formatting
        run: cd @voxel-definitions && deno fmt --check
      - name: Run tests
        run: cd @voxel-definitions && deno test --allow-net

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Publish package
        run: cd @voxel-definitions && deno publish
